# Generated by Django 3.1.3 on 2022-09-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220907_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RfidData',
            new_name='AttendanceRecord',
        ),
        migrations.RenameModel(
            old_name='UserData',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='name',
        ),
    ]
