# Generated by Django 3.1.3 on 2022-09-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20220907_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PureRfid',
        ),
    ]
