# Generated by Django 3.1.3 on 2022-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_delete_purerfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('a', 'accepted'), ('r', 'refused')], default='a', max_length=1),
        ),
    ]
