# Generated by Django 3.1.3 on 2022-09-25 15:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20220925_1157'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attendancerecord',
            managers=[
                ('manager_instance', django.db.models.manager.Manager()),
            ],
        ),
    ]
