# Generated by Django 3.1.3 on 2022-09-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20220925_1530'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attendancerecord',
            managers=[
            ],
        ),
    ]
