# Generated by Django 3.1.3 on 2022-10-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20220925_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user'),
        ),
    ]
